name: CaptionThis
options:
  deploymentTarget:
    macOS: "26.0"
  bundleIdPrefix: com.captionthis
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"

targets:
  CaptionThis:
    type: application
    platform: macOS
    sources:
      - path: CaptionThis
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.captionthis.CaptionThis
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: CaptionThis/Info.plist
        CODE_SIGN_ENTITLEMENTS: CaptionThis/CaptionThis.entitlements
        SWIFT_VERSION: "5.10"
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: false

